fm_elfinder:
    instances:
        default:
            locale: '%locale%' # defaults to current request locale
            editor: ckeditor # other options are tinymce, tinymce4, form, custom and simple
            fullscreen: false # defaults true, applies to simple and ckeditor editors
            #include_assets: true # disable if you want to handle loading of the javascript and css assets yourself
            connector:
                debug: false # defaults to false
                roots:       # at least one root must be defined
                    uploads:
                        #show_hidden: false # defaults to false
                        driver: LocalFileSystem
                        path: '%public_uploads%'
                        upload_allow: ['image/png', 'image/jpg', 'image/jpeg', 'application/pdf']
                        upload_deny: ['all']
                        upload_max_size: 5M
        admin_access:
            locale: '%locale%' # defaults to current request locale
            editor: simple # other options are tinymce, tinymce4, form, custom and ckeditor
            fullscreen: true # defaults true, applies to simple and ckeditor editors
            #include_assets: true # disable if you want to handle loading of the javascript and css assets yourself
            connector:
                debug: false # defaults to false
                roots:       # at least one root must be defined
                    private:
                        #show_hidden: false # defaults to false
                        driver: LocalFileSystem
                        path: '%private_uploads%'
                        upload_allow: ['image/png', 'image/jpg', 'image/jpeg', 'application/pdf']
                        upload_deny: ['all']
                        upload_max_size: 5M
                    public:
                        #show_hidden: false # defaults to false
                        driver: LocalFileSystem
                        path: '%public_uploads%'
                        upload_allow: ['image/png', 'image/jpg', 'image/jpeg', 'application/pdf']
                        upload_deny: ['all']
                        upload_max_size: 5M
        ck_editor:
            locale: '%locale%' # defaults to current request locale
            editor: ckeditor # other options are tinymce, tinymce4, form, custom and simple
            fullscreen: true # defaults true, applies to simple and ckeditor editors
            #include_assets: true # disable if you want to handle loading of the javascript and css assets yourself
            connector:
                debug: false # defaults to false
                roots:       # at least one root must be defined
                    public:
                        #show_hidden: false # defaults to false
                        driver: LocalFileSystem
                        path: '%public_uploads%'
                        upload_allow: ['image/png', 'image/jpg', 'image/jpeg']
                        upload_deny: ['all']
                        upload_max_size: 5M
                    private:
                        #show_hidden: false # defaults to false
                        driver: LocalFileSystem
                        path: '%private_uploads%'
                        upload_allow: ['image/png', 'image/jpg', 'image/jpeg', 'application/pdf']
                        upload_deny: ['all']
                        upload_max_size: 5M

        team_editor:
            locale: '%locale%' # defaults to current request locale
            editor: ckeditor # other options are tinymce, tinymce4, form, custom and simple
            fullscreen: true # defaults true, applies to simple and ckeditor editors
            #include_assets: true # disable if you want to handle loading of the javascript and css assets yourself
            connector:
                debug: false # defaults to false
                roots:       # at least one root must be defined
                    public:
                        #show_hidden: false # defaults to false
                        driver: LocalFileSystem
                        path: '%team_images%'
                        upload_allow: ['image/png', 'image/jpg', 'image/jpeg', 'application/pdf']
                        upload_deny: ['all']
                        upload_max_size: 5M