twig:
  default_path: '%kernel.project_dir%/templates'
  form_themes: [ 'bootstrap_5_layout.html.twig' ]


services:

  _defaults:
    autowire: true
    autoconfigure: true
    tags:
      - { name: twig.extension }

  App\Twig\:
    resource: "../../src/Twig"

  # >Not needed, has been replaced getProjectDir method of KernelInterface
  #App\Twig\AssetExtension:
  #    arguments:
  #        $rootDir: '%kernel.project_dir%'

when@test:
    twig:
        strict_variables: true
