# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:

    # File upload parameters
    public_uploads: "Offentlige filer"
    private_uploads: "../Private filer"

    # Profile photos
    profile_photos: 'images/Profile photos'

    # Logo images
    logo_images: 'images/Logo images'

    # Signature images
    signature_images: '../signatures'

    # Receipt images
    receipt_images: 'images/receipts'

    # Article images
    article_images: 'images/article_images'

    # Newsletter images
    newsletter_images: 'images/newsletter_images'

    # Team images
    team_images: 'images/team_images'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/{Role, Mailer, DataFixtures}'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Tests/'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Controller\:
        resource: '../src/Controller/'
        tags: ['controller.service_arguments']

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    App\DataFixtures\:
        resource: '../src/DataFixtures'
        tags: ['doctrine.fixture.orm']


    App\Google\GoogleService:
        abstract: true
        arguments: ['%google_api%', '@App\Service\LogService']

    App\Google\Gmail:
        parent: App\Google\GoogleService
        calls:
            - [setDefaultEmail, ['%default_from_email%']]

    App\Google\GoogleUsers:
        parent: App\Google\GoogleService

    App\Google\GoogleGroups:
        parent: App\Google\GoogleService

    App\Google\GoogleDrive:
        parent: App\Google\GoogleService

    App\Google\GoogleAPI:
        arguments: ['%google_api%', '@App\Google\GoogleUsers', '@App\Google\GoogleGroups']
