twig:
    default_path: '%kernel.project_dir%/templates'

services:

    _defaults:
        autowire: true
        autoconfigure: true
        tags:
            - { name: twig.extension }

    App\Twig\:
        resource: "../../src/Twig"

    App\Twig\AssetExtension:
        arguments:
            $rootDir: '%kernel.project_dir%'


